site_name: My projects
site_author: Jaszczur1969
site_url: https://github.com/Jaszczur1969/ds_ai_portfolio.git
site_description: >-
    See my Data Science and AI projects portfolio!

repo_name: Jaszczur1969/ds_ai_portfolio
repo_url: https://github.com/Jaszczur1969/ds_ai_portfolio.git

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
 
  
    
nav:
- Home Page: index.md
- Current projects:
  - "Insightly": Insightly/index.md
- Previous projects:
  - "EDA - Titanic (PL)": Titanic/index.md
  - "EDA - Iris (PL)": Iris/index.md
  - "Insurance predictor (EN)": Insurance predictor/index.md
  - "Time2Run (EN)": Time2Run/index.md
  - "Friend Seeker (PL)": Friend Seeker/index.md

markdown_extensions: 
  - attr_list
  - md_in_html
  - tables

plugins:
  - glightbox

extra_css:
  - css/extra.css