site_name: Moje projekty
site_author: Jaszczur1969
site_url: https://github.com/Jaszczur1969/ds_ai_portfolio.git
site_description: >-
    Portfolio moich projektów z Data Science i AI!

repo_name: Jaszczur1969/ds_ai_portfolio
repo_url: https://github.com/Jaszczur1969/ds_ai_portfolio.git

theme:
  name: material
  palette: 
    primary: blue
  
    
nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "Insightly": Insightly/index.md
- Poprzednie projekty:
  - "EDA - Iris (PL)": Iris/index.md
  - "EDA - Titanic (PL)": Titanic/index.md
  - "Insurance predictor (EN)": Insurance predictor/index.md


markdown_extensions: 
  - attr_list
  - md_in_html
  - tables

plugins:
  - glightbox